### ISSUE TITLE
Payment Links for connected accounts

### ISSUE THREAD

**Issue by adrian-schnell** [l4nos/laravel-cashier-stripe-connect#25]
I'd like to use the Stripe payment links whats the best practice to get this plugin work with this flow?

Is it necessary to create the subscription after a successful payment manually or does it work with webhooks?

**Comment by adrian-schnell** [comment]
> Cashier::stripe()->paymentLinks()->create();

thanks I'll give it a try @l4nos

**Comment by l4nos** [comment]
@adrian-schnell  I've since added in direct support for this. It's going out on the current release 1.12.1.

Please give it a try and let me know if it works for you. You can create both direct and destination payment links as well as some utility functions for updating links and retrieving the ones that sit directly within a connected account. (Direct Links)
