### ISSUE TITLE
$customer->hasCustomerRecord();

### ISSUE THREAD

**Issue by ngl5000** [l4nos/laravel-cashier-stripe-connect#34]
In the documentation it describes this workflow:

Now in order to create the connected customer, we must have a Connected account set up in order to take ownership this customer. For our example we will use our store model.

```
public function createStripeCustomer(Store $store, Customer $customer){

    $stripeCustomer = $customer->createStripeCustomer($store, $customerData);

}

After this, your customer model will now exist within stripe and thanks to the mapping, you will now be able to access and interact with this stripe customer from within your customer model. An outline of some functions are listed below.

Checking if a model exists as a stripe customer
The below function will return a boolean.

$customer->hasCustomerRecord();
```

but can't a connected customer have more than one customer with several stores? so won't this just check if any one exists? So if I have a user who is already a customer of store X but they want to buy something from store Y would this createStripeCustomer throw an exception?

```
    public function createStripeCustomer($connectedAccount, array $customerData = []){

        // Check if model already has a connected Stripe account.
        if ($this->hasCustomerRecord()) {
            throw new AccountAlreadyExistsException('Customer account already exists.');
        }
```

Sorry if this is obvious. I'm not well versed with this

**Comment by l4nos** [comment]
Thanks for the question, it isn't obvious so not a stupid question!

So it basically all depends on your business model. If the customer doesn't directly transact with the store, but rather purcahses from them via your app and your app is the merchant of record, then the customer exists once on the platform accuont and you use destination charges to charge the customer. A common real world example of this business model would be UberEats / DoorDash / JustEat / Takeaway.com. You order from the restaurant or store, but you actually pay the platform and they pay the store.

If the customer directly transacts with a merchant, a common example of this would be a Shopify store, (with you being shopify in this situation), then the customer has to exist once per merchant, as the merchants cannot share customers. If you are using Direct charges, the customer doesn't live inside your stripe account, it lives inside the stripe account of the merchant, and you simply associate that customer to a customer model in your record.

If you have a hybrid model where the customer transacts with the merchant but does so via a marketplace as opposed to D2C, then you'll need an additional table to map customers to merchants.

In that situation if you have 5 merchants all of which had the same customer "Mr Jones". "Mr Jones" would need to exist 5 times, across each merchant, one of the main reasons for this is Mr Jones legally transacts with the 5 stores separately, and may chose to provide different infomation to each of them, such as different delivery or billing details, segregation is important in that situation for data privacy reasons.

Happy to give further advice if needed, let me know if you have any more questions.

**Comment by ngl5000** [comment]
That is helpful. My situation is chess clubs collecting tournament entries.
The chess players are all users of the system and the clubs are their own
object. At the outset users don't have any direct relationship to the chess
club. They do however pay the chess club directly with my platform being
just a facilitator. I originally set this up with destination charges but
it didn't seem right since I unnecessarily had to get involved in refunds.
There was no good reason for the transaction to go through my account
first. In many cases, some people pay online and some people would pay the
club on site directly (which I think furthers the case for direct charges).
At the moment, I'm just not creating customers and using Stripes sdk to
generate the direct charge.

I hear what you are saying about the customer existing once per store, but
is that the stripe customer or the customer model on my side? What I'm
trying to do is take one user and allow them to be a customer of multiple
businesses. But the package is saying no no one user = one stripe customer.

**Comment by l4nos** [comment]
Thank you for providing additional context. Based on the information you've shared about your business model, it appears that the core aspect revolves around facilitating discovery for customers.

In many popular marketplaces, such as Etsy, eBay, Uber Eats, AirBnB, and OnlyFans, even though the customer is purchasing from another user or vendor, the platform itself is often the merchant of record. This is because by enabling customers to purchase from a particular seller, the platform is essentially endorsing and facilitating that transaction. While I'm not a legal expert, I strongly recommend seeking professional legal advice to ensure compliance with various consumer regulations.

In my experience, the vast majority of these platforms (around 99%) serve as the merchant of record and are inevitably involved in the dispute and refund process. This involvement provides credibility and reassurance to both merchants and customers. For instance, if I were to pay a local restaurant directly using my card and encountered an issue, resolving the dispute would be more challenging compared to placing an order through a platform like UberEats, where I could easily raise a dispute via the app. Although you may prefer to avoid this responsibility, doing so could potentially have a negative impact on your user acquisition efforts.

The only exceptions to this trend seem to be platforms that offer Software as a Service (SaaS) solutions, allowing merchants to transact directly through their own websites. Notable examples of this model include Shopify and Thinkific, which utilize destination charges.

My gut feeling is you will need to use destination charges for the reasons stated above, however, this does make your development and management of those customers far easier, as you customer exists once on the platform stripe account and once as a model within your database. Additionally, whilst your mind probablly conjures images of you being completely overwhelmed by refund, fraud chargebacks and disputes, the reality is this only happens like 2-5% of the time so by the time this actually becomes overwhelming, you'll have enough users and revenue to solve this problem via customer service team hires.

Lastly, if you aren't sure what to do about your use case, whether to use destination or direct charges, I'd consider consulting a legal advisor or even Stripes solution architect team, they are super helpful.

**Comment by ngl5000** [comment]
This is really helpful. I think with Standard accounts I could still get
involved based on the Platform Controls described here if I needed to:
https://support.stripe.com/questions/platform-controls-for-connected-accounts

I'll try to consult with Stripes team as you mention.

Thanks!

**Comment by jasonfish568** [comment]
> Thanks for the question, it isn't obvious so not a stupid question!
> 
> So it basically all depends on your business model. If the customer doesn't directly transact with the store, but rather purcahses from them via your app and your app is the merchant of record, then the customer exists once on the platform accuont and you use destination charges to charge the customer. A common real world example of this business model would be UberEats / DoorDash / JustEat / Takeaway.com. You order from the restaurant or store, but you actually pay the platform and they pay the store.
> 
> If the customer directly transacts with a merchant, a common example of this would be a Shopify store, (with you being shopify in this situation), then the customer has to exist once per merchant, as the merchants cannot share customers. If you are using Direct charges, the customer doesn't live inside your stripe account, it lives inside the stripe account of the merchant, and you simply associate that customer to a customer model in your record.
> 
> If you have a hybrid model where the customer transacts with the merchant but does so via a marketplace as opposed to D2C, then you'll need an additional table to map customers to merchants.
> 
> In that situation if you have 5 merchants all of which had the same customer "Mr Jones". "Mr Jones" would need to exist 5 times, across each merchant, one of the main reasons for this is Mr Jones legally transacts with the 5 stores separately, and may chose to provide different infomation to each of them, such as different delivery or billing details, segregation is important in that situation for data privacy reasons.
> 
> Happy to give further advice if needed, let me know if you have any more questions.

Think of eBay as the platform, a customer can make purchase with different sellers. Each seller has their own Stripe merchant account under eBay's main Stripe account. Does the customer exist 5 times under different merchant? Not necessarily. Like for a SaaS platform that a customer doesn't have to be individual to different players using this platform. It is usually the cusomter is a company and does not change its identities among different merchants on a SaaS platform. So it is totally due to different situation whether a customer should be set individually or can be the same one.

Moreover, that if a customer can only belong to one merchant, that merchant should setup direct charge instead of using the connected account feature. Because I don't see the point of having such an independent merchant under the platform's account.

I hope this helps you understand why I insist the point of a customer can belong to multiple merchants.

**Comment by l4nos** [comment]
Jason, I think you’re missing the point here. While it makes sense for a customer to exist only once, in Stripe, that’s not how it works. Each customer record is tied to a specific merchant. Please check Stripe’s documentation on direct charges and merchant of record to avoid giving misleading advice.

Using eBay as an example isn’t very relevant either. eBay doesn’t operate on a direct connected account model—they would likely use destination charges. Plus, they don’t even use Stripe; they own PayPal. If they were a Stripe user, they’d use destination charges because eBay acts as the merchant of record, managing disputes and chargebacks.

Please refrain from sharing inaccurate advice with users here. For anyone seeking clarification on my guidance, I encourage you to reach out directly to Stripe. I’ve developed a strong working relationship with Stripe, collaborating closely with them while building this platform for my payments company, so I have a solid understanding of how Connect functions.

If you continue to post misinformation that undermines genuine facts and potentially contributes to false / wasted development effortds from our users, i'll have to remove you from this repository.

**Comment by l4nos** [comment]
To further prove my point around customers exisitng multiple times, Stripe has a documentation page on cloning customer across connected accounts. If your customer only existed once, why would you need to clone them?? Because they don't exist once, they exist many times as the customer is a direct customer of that merchant.

https://docs.stripe.com/connect/cloning-customers-across-accounts?locale=en-GB

It's quite frustrating when users who have no real understanding of Stripe's model, make unhelpful and untrue ocmments that lead to potentially damaging development efforts.

@ngl5000 as I said, if you want help, reach out.
