### ISSUE TITLE
Fallback creating products on main account

### ISSUE THREAD

**Issue by jasonfish568** [l4nos/laravel-cashier-stripe-connect#39]
If the connected account has not been set up on Stripe, when creating products, it won't have Stripe-Account added to the header of the request. Therefore the porducts are added to the main account.

**Comment by l4nos** [comment]
Why would you want the products to add to the main account as a fallback. The two should be separate.

If you are trying to add products to a stripe connected account that does not exist yet, then it should throw an exception.

If you need to add products to the platform stripe account, this should be done using traditional Cashier.

**Comment by jasonfish568** [comment]
Please read my description again. This is a bug, not a feature request.

```
    /**
     * The default Stripe API options for the current Billable model.
     *
     * @param array $options
     * @param bool $sendAsAccount
     * @return array
     */
    public function stripeAccountOptions(array $options = [], bool $sendAsAccount = false): array
    {
        // Include Stripe Account id if present. This is so we can make requests on the behalf of the account.
        // Read more: https://stripe.com/docs/api/connected_accounts?lang=php.
        if ($sendAsAccount && $this->hasStripeAccount()) {
            $options['stripe_account'] = $this->stripeAccountId();
        }
        
        // Workaround for Cashier 12.x 
        if (version_compare(Cashier::VERSION, '12.15.0', '<=')) {
            return array_merge(Cashier::stripeOptions($options));
        }

        $stripeOptions = Cashier::stripe($options);
        
        return array_merge($options, [
            'api_key' => $stripeOptions->getApiKey()
        ]);
    }
```


Clearly that only if the current account has Stripe Account, it will then add $options['stripe_account']. Without this option, products are added to the main account.


And in ManageConnectProducts.php:

```
    /**
     * Creates a stripe product against the connected account
     * @param $data
     * @return Product
     * @throws ApiErrorException
     */
    public function createConnectedProduct($data): Product
    {
        return Product::create($data, $this->stripeAccountOptions([], true));
    }
```

It's suppose to verify if the account hasStripeAccount() before creating.

I don't know why you close issues so quick without even understanding the question. Also, last time I pointed out your logic error that a customer can belong to multiple merchants but you denied. The truth is a customer indeed can belong to multiple merchants and this is how a connected account works. 

If you are just building a project for yourself then don't even bother the issue tracker. But if you are building a project and do want to make it better, be patient. Bugs are annoying but a revealed bug is better than a hidden one.

**Comment by l4nos** [comment]
I closed the issue because your initial description was only two lines and poorly worded. Now that you’ve provided more detail, I can see the issue clearly.

You can use the $entity->assertAccountExists(); function before creating your product. I will include that function and add that into each of the product functions as part of the next release. In the menatime, you can include the function yourself before the product creation statement.

`
   /**
     * Creates a stripe product against the connected account
     * @param $data
     * @return Product
     * @throws ApiErrorException
     */
    public function createConnectedProduct($data): Product
    {
        $this->assertAccountExists();
        return Product::create($data, $this->stripeAccountOptions([], true));
    }
`

Whilst bringing previous feelings and issues into this issue thread may not appropriate or relfective of the purpose of individual issues, i'll still acknowledge and address it below. 

My feedback wasn't about flaws in your practical logic but in your understanding of Stripe’s functionality. Regardless, it was certainly not a logic error on my part.

When a customer transacts with multiple merchants using DIRECT charges, they will have separate customer records within each merchant’s connected account. This setup reflects the fact that each customer belongs to a specific merchant for that transaction. For Destination charges, however, the platform is the merchant of record, so the customer can exist as a single entity in your database, as they’re technically your customer. I’d recommend reviewing Stripe's documentation to better understand "merchant of record" and its implications.

If you review past issues, you’ll see that I've acknowledged and resolved others' concerns and even accepted PRs that added value. The issue here isn’t my approach.

Responding with rudeness and condescension when others question or highlight gaps in your approach is unproductive and the suggestion that I do not want to help others is simply not correct. I would ask that you consider this and revise your approah on future issues. I'll reopen this until the aforementioned relaese is made.

**Comment by l4nos** [comment]
I can see from looking over past issues, you've been spreading misinformation about how Stripe works and undermining the efforts of contriubutors to this plugin.

You've been removed from this reporisotry. Banned from posting and commenting.
